apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flash-app
  template:
    metadata:
      labels:
        app: flash-app
    spec:
      containers:
        - name: flash
          image: marlonalvesilva/flash-kub-projeto:3
